name: Node.js CI

on:
  push:
    branches:
      - main
    paths:
      - '**.ts'
      - package.json
      - yarn.lock
  pull_request:
    branches-ignore:
      - 'renovate/**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i -g yarn
    - run: yarn install
    - run: yarn build
    - run: yarn lint

    - env:
        FANDOM_PASSWORD: ${{ secrets.FANDOM_PASSWORD }}
        FANDOM_USERNAME: ${{ secrets.FANDOM_USERNAME }}
        FANDOM_WIKI: bitomic

      run: yarn test
